<?xml version="1.0" encoding="utf-8"?><Database Name="Login" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DSACTOL\SQLEXPRESS;Initial Catalog=Login;Integrated Security=True" SettingsObjectName="AccountantManager.Properties.Settings" SettingsPropertyName="LoginConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Clientes">
      <Column Name="IDCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre_RazonSocial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CUIL_CUIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>